# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole website, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A personal site of an academic
email: firstname.lastname@amazing.org
description: >- # this means to ignore newlines until "baseurl:"
  Please fork and edit. Happy building!
  Copyright 2022 Cheng Soon Ong.
baseurl: "/academic-site" # the subpath of your site, e.g. /blog.
url: "https://chengsoonong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  chengsoonong

# Build settings
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
